### ISSUE TITLE
Installation instructions in readme

### ISSUE THREAD

**Issue by Axolotlke** [teamdeeson/warden#107]
In the readme file under installation instructions it says to run composer update to get started.

This should be "composer install", so it uses the versions in the shipped lock file. Update will update all packages to their latest version. This will also update Twig to the latest 2.x version which requires PHP7, making it unable to run on a PHP 5.6 environment.

Also, there's a typo in the scripts foldr name in this command :

./script/clear-cache.sh [ENV]` 

should be

./scripts/clear-cache.sh [ENV]`

**Comment by mikeddeeson** [comment]
Hi @Axolotlke,

Good spot, thanks 😄 

I'll update the readme file with these details.

Thanks
Mike

**Comment by mikeddeeson** [comment]
Thanks @ashleydeeson, I have updated this readme file now, which will be in the next release 😄
