### ISSUE TITLE
Site-update can't handle string 'disabled' as value for details that should be ignored

### ISSUE THREAD

**Issue by jcalais** [teamdeeson/warden#112]
The Drupal module does not send an empty array, but rather the string value 'disabled' if Third Party Libraries aren't included in the data set.

This causes SiteDocument::setLibraries() to foreach iterate over the string 'disabled' and makes site-update fail with 'Bad request'.

I noticed the Drupal module sets the value 'disabled' for all excluded types of data, which means this error may affect other parts of the Warden server site-update route as well. You can verify this in WardenManager.php from line 143.

Steps to reproduce:

1. Setup a Drupal site with the warden module and configure it.
2. Make sure the warden_match_library setting is FALSE (the default) on your Drupal site.
3. Run a site update against your Warden server from the Drupal site using drush warden-update
4. You should see a Bad request error.

**Comment by mikeddeeson** [comment]
Hi @jcalais, thanks for using Warden. 

This is an unfortunately bug, but thanks for the pull request I will have a look at that and get this into the next bug release.
