### ISSUE TITLE
Provide example nginx/apache config

### ISSUE THREAD

**Issue by legolasbo** [teamdeeson/warden#121]
@mikeddeeson I'm trying to install warden on a nginx server, but can't seem to get it to work. Could you please provide an example nginx config file that should work with warden or at least point me in the right direction?

Thanks in advance! :)

**Comment by mikeddeeson** [comment]
Hi @legolasbo ,

As this is a standard Symfony app, you should be able configure Nginx to run based upon their docs - https://symfony.com/doc/2.8/setup/web_server_configuration.html#nginx.

Is there something specific that you are having problems with or is it just the general set up?

Thanks
Mike

**Comment by legolasbo** [comment]
Thanks for the quick feedback!

I'll give that a go and report back.

**Comment by mikeddeeson** [comment]
Did you manage to get your server configured all ok @legolasbo?

**Comment by legolasbo** [comment]
Not yet, but the issue seems to lie with another site's config taking precedence over warden's. I'll get back to you once we've got it all sorted out. Currently some client work has priority over this.

**Comment by mikeddeeson** [comment]
No problems .... thanks for the update. I'll keep this thread open for the time being then

**Comment by legolasbo** [comment]
Got it working, turned out to be an issue with the default site config of another site.

**Comment by mikeddeeson** [comment]
Thanks for the update @legolasbo and glad that you managed to get it sorted out 😄
