### ISSUE TITLE
Not generating keys

### ISSUE THREAD

**Issue by Opswatch** [teamdeeson/warden#136]
Hi

I have been trying to install warden and no matter what I try it wont generate the keys, I have tried specifying the path for example '/home/warden/app/config/public.key' and also without the ' and for some reason it does not get generate even with a fresh ubuntu vm, any ideas?

**Comment by mikeddeeson** [comment]
Hi @Opswatch 

Thank you for trying out Warden 👍 

The SSL keys are generated by the app and saved to the file system, so if these aren't be created it is likely that the file/ folder permissions aren't correct for the location where you want the keys to be generated. 
Do you have the correct permissions on the server where these files will be add to?

Thanks
Mike

**Comment by Opswatch** [comment]
I am guessing the user has rights, I am able to create the keys manually with the same user, I created a /config folder in the root path to keep it as close to default as possible just to test. Tried it both on a docker container and a vm. I was able to work around it by manually creating them, but its interesting that its not generating them automatically.

**Comment by mikeddeeson** [comment]
Having had a look, it would be the web server user that would need access to create the files as it is the app that generates and creates the keys if they don't exist.

If the system fails to generate the keys it will throw an exception, which will be logged in the logs as  I imagine that you are running it in production mode?
The exception message will start with "`Unable to save security key to`", so you could see if this has come up in your log files.

You could try setting the file location to be somewhere like the `tmp` directory (as I think all users have access to write to this directory) to see if they are generated just to show that they can be generated.

**Comment by mikeddeeson** [comment]
Hi @Opswatch - did you manage to get this working and being able to generate your keys correctly?

**Comment by Opswatch** [comment]
Hi I managed to get around it by setting the docker container to manually generate the keys during the build, ill close this up for now.

**Comment by mikeddeeson** [comment]
Thanks for the update @Opswatch, glad that you managed to get it sorted out 😄
