### ISSUE TITLE
Add database username/ password details to install

### ISSUE THREAD

**Issue by mikeddeeson** [teamdeeson/warden#14]
Currently the mongo database doesn't have a username and password to access it, so is open for access.  

In order to the mongo database, the username and password will need to be added along with an update to the install process to ask for them.  These details will then need to be added the parameters.yml file.

Instructions should be added to the README file for securing a mongodb installation.

**Comment by asrob** [comment]
+1 from me, it would be a great feature to use warden in production environment.

**Comment by mikeddeeson** [comment]
OK thanks .... I dropped this from the next release for the time being so that we can focus on getting the other items done. 

If everything goes well I _might_ be able to get this work added back into this next release .... :)

**Comment by asrob** [comment]
Thank you very much, Mike! :)

**Comment by asrob** [comment]
I would propose this issue to be in the "beta5". :)

**Comment by mikeddeeson** [comment]
Hi @asrob,

Here is a pull request which adds support for using authenication with your Mongodb server. Please have a look and let me know how you get on.

Thanks
Mike
