### ISSUE TITLE
Any reason connection times out 50% times?

### ISSUE THREAD

**Issue by hkirsman** [teamdeeson/warden#140]
I get "General Error - Unable to retrieve data from the site: Operation timed out after 20000 milliseconds with 0 bytes received" when doing "Refresh Site Data" about 50% of time. Anything obvious to check? Should I somehow increase the 20 seconds interval? Which is odd is that if the connection works then it's pretty instant (under 1 sec).

**Comment by mikeddeeson** [comment]
Hi @hkirsman 

The fact that it happens about 50% of the time might indicate that there is a connect issue between the server that you have Warden installed on and the server that is hosting your site.

Can you curl the site you are connecting to from the warden server repeatedly to see if you get the same problem of it not being able to connect about 50% of the time?

Also are there any errors generated for the site that you are trying to connect to from Warden?

Thanks
Mike

**Comment by hkirsman** [comment]
I could connect from Warden server but not from the server where site is. 

And yes it seemson Drupal side there are logs when Warden server has failed (replaced our domain with example.com but the end is correct.:
http://example.com/public-key : -110 : Connection timed out

@mikeddeeson

**Comment by mikeddeeson** [comment]
This sounds like it is having problems communicating with your warden server.

Are you able to curl it from your sites server to see if you are getting problems?

**Comment by hkirsman** [comment]
Hm, I think I did that already  - "I could connect from Warden server but not from the server where site is." So I did test both ways.
Warden -> Site = OK
Site -> Warden = Not ok

So yes, something wrong with communication but it's weird that curl doesn't work 100%. It could be something to do with the fact that Warden server can't be accessed from public side so I try to figure out what configuration is behind that.

**Comment by mikeddeeson** [comment]
mm ... that is odd. At least you have something to investigate further 😄
