### ISSUE TITLE
No updates displayed

### ISSUE THREAD

**Issue by DaisyMaeHarris** [teamdeeson/warden#142]
Hello, I've installed the dashboard and connected two Drupal 7 sites. There are no error messages in the Drupal log, and the ./scripts/cron.sh command does not show any errors.

The Dashboard says "There are currently no modules registered" and "There are currently no third party libraries registered." even though everything seems fine. How do I register them?

Many Thanks

**Comment by mikeddeeson** [comment]
Hi @DaisyMaeHarris 

Have you registered your two sites with the warden server - in that are they showing up in the sites lists? Did you click the register button on the Drupal sites within the Warden config page?

As long as you have at least one site showing in the sites list, then when you run the cron script this will gather the data needed from Drupal.org as well as the sites.

If there has been connection errors between the sites and the Warden server then you should be able to see this in the sites page as there is a request log.

Also it is worth checking the Warden server logs when you are running the cron script as this will provide some further details about any errors the may have occurred during the running of this script.

The main dashboard only shows sites that have got errors, whereas the sites list will list all the sites that you have registered with Warden.

**Comment by DaisyMaeHarris** [comment]
Thank you, I have registered both sites with the Warden server and the sites show up in my sites list fine - I clicked the register button on the Drupal sites within the Warden config page and all seemed to go smoothly. 

The requests log for both sites looks good and have run Cron on both. It’s all very mysterious. 

I’ve been checking the error log at /var/logs/error.log is there a different place I ought to be looking? Knowing where to find some errors would be a great help with troubleshooting further.

There are module updates needed on both sites but nothing is showing up in the dashboard. It’s very mysterious indeed. 

Thanks again

**Comment by mikeddeeson** [comment]
Have you been running cron on the Drupal sites or the Warden server?

The cron should be run from the Warden server as this is what connects to the Drupal sites and to Drupal.

The Warden server logs are found in app/logs within the Warden server.

**Comment by DaisyMaeHarris** [comment]
Thank you, that sounds really helpful. I have been running crons from both ends. I’ll check the error logs.
Many Thanks

**Comment by mikeddeeson** [comment]
Hi @DaisyMaeHarris, 

Running cron on the Drupal site doesn't do anything as it is the Warden server that requests data from the sites. 
We have shipped a drush command with the Drupal module to send the data to the server.

Thanks
Mike

**Comment by DaisyMaeHarris** [comment]
Thank you 

`drush warden-check` gets the public key absolutely fine, `drush warden-show-module-data` lists the modules fine but `drush warden-update` gives an error: `400 : Bad Request [error] Unable to communicate with Warden`

There doesn't seem to be a logs directory in the app directory as described, instead I have found a log file at /var/logs/prod.log which shows these three errors:

```
[2019-04-08 13:48:17] php.INFO: User Deprecated: The "logger" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"logger\" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. at /mywebsite.com/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:282)"} []

[2019-04-08 13:48:17] php.INFO: User Deprecated: The "warden.ssl_encryption" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"warden.ssl_encryption\" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. at /mywebsite.com/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:282)"} []


[2019-04-08 13:48:17] app.ERROR: Update http://default : No such site registered with Warden: http://default [] []
```

**Comment by mikeddeeson** [comment]
Hi @DaisyMaeHarris 

It sounds like you are using the latest version from the `develop` branch which is still in development ready for the next major release. Ideally you should be using one of the release versions if you would like a stable release.

The error message in Warden is telling you what is going on: 
`Update http://default : No such site registered with Warden: http://default `

Your site has given the host name of 'default' to your Warden server when it was registered.

**Comment by mikeddeeson** [comment]
You can continue to use the develop branch if you don't mind it potentially breaking as it is the latest development that is going on 😄 

I would suggest that you checkout the latest release tag 1.4.0 as this is the latest release version.

**Comment by DaisyMaeHarris** [comment]
Thank you, that's very useful. I have installed 1.4.0 and now see app/logs/dev.log.

It does seem that all of my Drupal websites have location http://default/ - where is this set and how may I change it?

Thank you

**Comment by mikeddeeson** [comment]
The configuration of your Drupal sites needs to set the $base_url (I think it is) to set the domain correctly for Drupals configuration. You should configure your Drupal sites correctly so that it reports it to Warden with the correct domain name.

Once you have got that configured correctly on your Drupal sites, you can change the domain that has been registered with Warden by editing the site(s).

**Comment by DaisyMaeHarris** [comment]
Thank you so much, I really appreciate your prompt and helpful replies. I’ll get to work on that right away.

**Comment by DaisyMaeHarris** [comment]
Just leaving my solution in case it might be helpful to anybody else. My environment did not have the drush uri defined - if you encounter the same http://default issue then you will either need to add $options['uri'] = ‘http://yourdrupalwebsite.com’; to a sites/default/drushrc.php file, or define --uri when you run the command: `drush --uri=http://yourdrupalwebsite.com warden-update`
