### ISSUE TITLE
Route outbound request

### ISSUE THREAD

**Issue by rhiannonpurnellms** [teamdeeson/warden#145]
Thanks for the great dashboard. I am hosting it on Heroku (which has dynamic IPs) - the Warden Drupal module requires the whitelisting of the dashboard IP so I am attempting to re-route the outgoing request through a static IP address. I am using an app called Fixie which provides the following code example - do you know roughly where this might go within the Warden Symfony application?

```
<?php
  function proxyRequest() {
    $fixieUrl = getenv("FIXIE_URL");
    $parsedFixieUrl = parse_url($fixieUrl);

    $proxy = $parsedFixieUrl['host'].":".$parsedFixieUrl['port'];
    $proxyAuth = $parsedFixieUrl['user'].":".$parsedFixieUrl['pass'];

    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_PROXY, $proxy);
    curl_setopt($ch, CURLOPT_PROXYUSERPWD, $proxyAuth);
    curl_close($ch);
  }

  $response = proxyRequest();
  print_r($response);
?>
```

**Comment by johnennewdeeson** [comment]
Hi, the maintainer is away on Sabatical until mid September so you might not get a quick reply to this.

I'm pretty sure the IP whitelisting is optional though (if recommended) - there'a a lot of security mechanisms to ensure the request is coming from a trusted source, including a unique public/private key pairing.  

You can disable IP whitelisting inside the Drupal module.  With the Drupal 7 version this would involve setting the `warden_public_allow_ips` Drupal variable to an empty string and something similar with the Drupal 8 module.

**Comment by rhiannonpurnellms** [comment]
That's really helpful, thank you.
