### ISSUE TITLE
Email alerts

### ISSUE THREAD

**Issue by mikeddeeson** [teamdeeson/warden#20]
The Warden application could do with sending out weekly emails with a list of sites that are out of date to keep relevant people aware of these.

**Comment by asrob** [comment]
+1, this would be awesome! :)

**Comment by asrob** [comment]
I would propose this issue to be in "beta5" release. :)

**Comment by mikeddeeson** [comment]
OK, lets consider this one for beta5 release as it would be a good addition. Just need to have a think around the sending and format of the emails :)

**Comment by asrob** [comment]
Cool!

Thanks, Mike! :)
