### ISSUE TITLE
Remove Drupal specific code from the SiteDocument class

### ISSUE THREAD

**Issue by johnennewdeeson** [teamdeeson/warden#26]
SiteDocument needs to be generic for any site, currently there are Drupal specific items in there which should be moved to the Drupal Site Service

**Comment by mikeddeeson** [comment]
In line with the work that is being done for #9, this will be updated so that the SiteDocument only has information very specific to a site

**Comment by mikeddeeson** [comment]
As part of the work done for #9, the class was updated
