### ISSUE TITLE
Detect obsolete/unsupported versions

### ISSUE THREAD

**Issue by ghost** [teamdeeson/warden#41]
My site has the media_youtube module installed, version 7.x-2.0-rc4. Drush says I need 7.x-3.0 because "Installed version not supported".

Could Warden let me know this too?

**Comment by mikeddeeson** [comment]
This is something that needs to looked at and highlighted on the module list for a site.

We could possibly do with a section which maybe lists out all the unsupported modules that are being used across the sites, with a list of those sites using the module?

I have noticed that this also raises an issue when the supported version of the module then has a security update. In this case the unsupported version that a site is using is not highlighted as needing a security update as there is no security update for this release version. 

e.g. Google Analytics has a 1.x release, which is no longer supported.  The 2.x release has a security update, so any sites using the 1.x release should really be updated to the latest 2.x release.

**Comment by mikeddeeson** [comment]
In the first instance for this we will look at highlighting unsupported versions within the module listing on a site.

At a later date we can look at producing a separate list of modules which have sites that are using unsupported versions if this would be something that is useful.

**Comment by mikeddeeson** [comment]
Hi @ghost, I have been working on this feature and I have a working version on a branch currently. Once I have been able to do some further testing on this to check that it is working correctly I will be able to push this so that this will be available for you in a new release.
