### ISSUE TITLE
Drupal: Sometimes modules are not flagged as needing a security update

### ISSUE THREAD

**Issue by johnennewdeeson** [teamdeeson/warden#47]
A site had display suite (ds) 7.x-2.6 installed. 7.x-2.8 release was tagged as security. 7.x-2.11 is the latest release.  ds on this site should be marked as needing a security update in Warden but is not being.

![image](https://cloud.githubusercontent.com/assets/1913439/10509218/84764a4c-7323-11e5-99a7-5d7e4d828d27.png)

**Comment by mikeddeeson** [comment]
This has now been committed and updated
