### ISSUE TITLE
How to get installed modules?

### ISSUE THREAD

**Issue by asrob** [teamdeeson/warden#50]
Hi!

I installed drupal module and warden "server". I successfully configured it, I got core version correctly but I didn't get modules list. I'm using warden server in dev mode, but how do I get modules list?

Here is my settings.php:

> $conf['warden_server_host_path'] = 'http://104.155.109.228';
> $conf['warden_public_allow_ips'] = '104.155.109.228,127.0.0.1,::1,127.2.2.1';
> $conf['warden_allow_requests'] = 'TRUE';
> $conf['warden_match_custom'] = 'TRUE';
> $conf['warden_preg_match_custom'] = '{^sites\/([A-z,\.,\-]+)\/modules\/custom\/*}';
> $conf['warden_match_contrib'] = 'TRUE';
> $conf['warden_preg_match_contrib'] = '{^sites\/([A-z,\.,\-]+)\/modules\/contrib\/*}';
> $conf['warden_match_core'] = 'TRUE';

![screen shot 2016-02-02 at 19 56 32](https://cloud.githubusercontent.com/assets/251897/12760541/235e8c7c-c9e7-11e5-99ef-670645383e62.png)

**Comment by johnennewdeeson** [comment]
Hi!

Thanks for testing out - can you try running the cron scrip a couple of times? Something like the following assuming you are using the dev environment...

    ./bin/cron.sh @dev

**Comment by johnennewdeeson** [comment]
Sorry, its actually in the scripts folder so ...

    ./scripts/cron.sh @dev

**Comment by asrob** [comment]
@johnennewdeeson yeah, I ran it but no success. :(

![screen shot 2016-02-02 at 20 03 28](https://cloud.githubusercontent.com/assets/251897/12760740/23dae15e-c9e8-11e5-99f9-3f8931e40eda.png)

**Comment by asrob** [comment]
Anyway I use dev version ( git clone ) of server.

**Comment by johnennewdeeson** [comment]
Thanks for the screen shot - the lack of errors suggests its working but not sending the modules across which might be because of the regex which tries to locate the modules.  I'll checkout the Drupal module to see what happens when modules are installed somewhere other than sites/all/modules/contrib

**Comment by asrob** [comment]
@johnennewdeeson yes, my fault. I download modules to sites/default/all/modules directory, therefore that regex I added into settings.php was wrong. Creating "contrib" directory and put them into it, it seems to work.

Thank you for super fast answers
![screen shot 2016-02-02 at 20 13 52](https://cloud.githubusercontent.com/assets/251897/12761004/956e4bde-c9e9-11e5-90c9-10ce265d9579.png)
! :)

**Comment by johnennewdeeson** [comment]
Awesome!
