### ISSUE TITLE
Dashboard is empty

### ISSUE THREAD

**Issue by asrob** [teamdeeson/warden#51]
I added 2 sites, ran cron and build-dashboard.sh but my dashboard is still empty. Is it not working yet?

![screen shot 2016-02-02 at 20 18 43](https://cloud.githubusercontent.com/assets/251897/12761269/885e7da0-c9ea-11e5-8a21-a56ab0aee1be.png)

**Comment by johnennewdeeson** [comment]
Its not clear but the Dashboard only lists sites with urgent security fixes - hopefully you have no sites with pending security issues so nothing appears here.

**Comment by asrob** [comment]
Aha... cool. :)

Sorry for a lot of questions, I would tag it with label but I cannot. I work for a hungarian drupal company and I look for a tool to monitor our sites and their updates. Warden is really impressive but still missing some functions. Now, I can contribute it as tester or a translator but in longer term as developer.

And again, thanks for quick reply!
