### ISSUE TITLE
Installation bug: unable to create warden-custom.css

### ISSUE THREAD

**Issue by damienmckenna** [teamdeeson/warden#58]
When I ran "composer install" it failed with the following:

```
 - Setting up the CSS file ...
Script Deeson\WardenBundle\Composer\ScriptHandler::setupWarden handling the post-install-cmd event terminated with an exception

  [ErrorException]

file_put_contents(/Users/dmckenna/Sites/warden/app/../src/Deeson/WardenBundle/Resources/public/css/warden-custom.css): failed to open stream: No such file or directory
```

The problem was that the 'src/Deeson/WardenBundle/Resources/public/css' directory didn't exist.

**Comment by mikeddeeson** [comment]
Thanks @damienmckenna for this - I now have a clean box that I am working from and I have got the same error as you have here so I can look at getting this corrected.

**Comment by mikeddeeson** [comment]
Hi @damienmckenna - sorry for the delay in getting back to you on this, but I have now fixed this issue in the installer.
