### ISSUE TITLE
Login page doesn't log in

### ISSUE THREAD

**Issue by drclaw** [teamdeeson/warden#59]
Attempting to log in for the first time. The log in page just reloads with no error message or feedback.

I scanned through the installation feedback. I did get the css file creation error mentioned in #58, but after manually creating the missing folder, I was able to complete the installation by running `php app/console deeson:warden:install --regenerate` ... not sure if that's relevant, but it's the only issue I could see during installation.

**Comment by mikeddeeson** [comment]
Hi @drclaw, thanks for looking at our application.

As part of the installation, the system will generate a config file which contains the user credentials. There should be a file located in 'app/config/' called 'warden-security.yml'.

Running `php app/console deeson:warden:install --regenerate` will generate the credentials for the login, so it sounds like the file might be missing - maybe permissions issue?

Does this file exist on your file system?

Thanks
Mike

**Comment by drclaw** [comment]
Hey @mikeddeeson 

Thanks for the reply! I've checked and the warden-security.yml file is there with the admin username and a hashed password. Any other ideas? :)

**Comment by mikeddeeson** [comment]
Hi @drclaw,

Sorry for not coming back to you on this previously, I have just noticed this in the list of issues when I was going through them.

Are you still having this problem or has it been sorted out now as this seemed to be a very strange issue that you were having.

Thanks
Mike
