### ISSUE TITLE
Update warden to use newest and official mongodb driver

### ISSUE THREAD

**Issue by asrob** [teamdeeson/warden#61]
I think it would be good to update warden to use newset and official mongodb PHP driver. There is other issue where you discussed about mongodb version: #60

**Comment by mikeddeeson** [comment]
This is currently being worked on on a separate branch - mongodb-32.

Once we have this tested and ready we will be able to merge this back into the master branch.

**Comment by mikeddeeson** [comment]
The `mongodb-32` branch has been merged to the `master` branch which updates this driver version
