### ISSUE TITLE
Drupal: Incorrect identification of module/ core versions

### ISSUE THREAD

**Issue by damienmckenna** [teamdeeson/warden#62]
I run a local dev copy of Drupal core and contrib modules where literally _everything_ is checked out using git. Currently my core release is 7.51-dev. I hooked it up to Warden and it shows the following message:

> Alert! There is a core security update required for this site: 7.50

The logic for matching version numbers needs to recognize that 7.51-dev is higher than 7.50.

**Comment by mikeddeeson** [comment]
Hi @damienmckenna,

Thanks for this, it does look like the module version check isn't checking the dev releases for core whereas we are for module versions.

From an initial look, it seems that the regex check in the ModuleDocument (src/Deeson/WardenBundle/Document/ModuleDocument.php line 331) needs to be updated from:

`preg_match('/([0-9]).([0-9]+)/', $version, $matches);`

to:

`preg_match('/([0-9]).([0-9]+)([a-z0-9\-+]+)?/', $version, $matches);`

I haven't tested this in the application yet, but the regex would match the core dev release.

Does this work for you dev release site?

Thanks
Mike

**Comment by mikeddeeson** [comment]
Hi @damienmckenna, 

I have updated the way that the checks for the core version is handled which should fix your issue.

Thanks
Mike
