### ISSUE TITLE
Drupal: Remove modules that are no longer in being reported on from the site

### ISSUE THREAD

**Issue by mikeddeeson** [teamdeeson/warden#66]
Currently if a site has a module removed from it, than this module is not removed from the listing against the site when performing an update. This leafs to it incorrectly reporting issues.

**Comment by mikeddeeson** [comment]
I have tested this and this does seem to be working correctly - I must have had some funny data at the time.

**Comment by johnennewdeeson** [comment]
Hi @mikeddeeson - Seeing this happening on our production site.

**Comment by mikeddeeson** [comment]
This appears to be working correctly and turned out to be a problem with the sites module data rather than Warden.
