### ISSUE TITLE
Update README file with details of the different mongodb drivers

### ISSUE THREAD

**Issue by mikeddeeson** [teamdeeson/warden#74]
Now that we have updated the driver version to the latest version, we need to update the README to provide details of how users can use the old legacy mongodb driver if they are running this server software on an older version.

**Comment by asrob** [comment]
Hi @mikeddeeson,

as I can see this is the last issue with tag beta4. This means that you will release a new version soon?! :)

**Comment by mikeddeeson** [comment]
Hi @asrob, 

Yes, I will be reviewing this README file today to update it and can then cut the next beta release :)
