### ISSUE TITLE
Update Symfony to 2.8.x LTS and Twig to the latest stable

### ISSUE THREAD

**Issue by mikeddeeson** [teamdeeson/warden#85]
The Symfony version detailed in the composer.json file is current 2.6.*, which ended support in 2015, so we need to update this to 2.8.* to bring the application inline with the available LTS version.

**Comment by asrob** [comment]
I would propose this issue to be in beta5. :)

**Comment by mikeddeeson** [comment]
The pull request for this has been merged in now and the develop branch updated.

Thanks @asrob
