### ISSUE TITLE
Create a plugin system

### ISSUE THREAD

**Issue by johnennewdeeson** [teamdeeson/warden#9]
Make it so that plugins can be made to allow for non Drupal sites to be listed on the Dashboard and custom report types

**Comment by mikeddeeson** [comment]
In line with this, now that there are several events added to the system around the various actions on a site, we should look to move any Drupal specific code to a new bundle called WardenDrupalBundle, which will separate it off to make a step towards building a more modular system for other providers such as Wordpress etc.

**Comment by mikeddeeson** [comment]
Having started working on this, this will involve too many document data changes, so I am moving this to be part of the 2.0 release due to this number of changes
