### ISSUE TITLE
Debugging connection issues

### ISSUE THREAD

**Issue by artursv** [teamdeeson/warden#91]
Hi!

I`m having issues with connecting two of our sites to the dashboard. Both have the same symptoms as far as I can tell.

Dashboard log:
> [2017-01-27 15:09:51] app.ERROR: Unable to request data from http://www.mysite.com/admin/reports/warden Status code: 403 Headers: Array (     [0] => HTTP/1.1 403 Forbidden     [1] => Content-Type: text/html; charset=utf-8     [2] => Vary: Accept-Encoding     [3] => X-Drupal-Cache: MISS     [4] => Expires: Sun, 19 Nov 1978 05:00:00 GMT     [5] => Cache-Control: no-cache, must-revalidate     [6] => X-Content-Type-Options: nosniff     [7] => Content-Language: xx     [8] => X-Frame-Options: SAMEORIGIN     [9] => Transfer-Encoding: chunked     [10] => Date: Fri, 27 Jan 2017 13:09:04 GMT     [11] => Age: 0     [12] => Connection: keep-alive     [13] => X-Varnish-Cache: MISS )  [] []

Drupal log:
> Update request denied: Failed to validate security token in request at timestamp 1485522558

Both site settings.php files contain the same Warden configuration (also the same as 2 other sites that connect just fine). Does the Drupal sites has to have a valid SSL certificates to be able to connect to dashboard?

Any advice will be appreciated,
A.

**Comment by mikeddeeson** [comment]
Hi @artursv,

Thank you for your interest in Warden and reaching out.

The Drupal error log seems to provide the reason for the connection problems - the timestamp difference. 

For security reasons, requests from the Warden server to the Drupal module go through various checks to validate them. One of these checks is against the timestamp of the request against the current timestamp on the Drupal server. If the request timestamp is not with +-20 seconds of the Drupal server timestamp then the request will fail.

Do you have something like NTP running on both the Warden server and the Drupal servers?

Thanks
Mike

**Comment by artursv** [comment]
Hi @mikeddeeson,

The time difference was indeed the issue. I fired up ntpd process to sync up the time and I was able to connect to the dashboard. Would it be possible to make this time frame configurable? For the most part I think it`s not necessary but for some edge cases might come in handy. 

A.

**Comment by mikeddeeson** [comment]
Hi @artursv,

Glad that that fixed it for you.

I would think that all your servers should ideally be running NTP so they should be in sync for the time.

If you can think of an edge case where this would cause an issue I would be happy to discuss further to see if there is the need to make this configurable.

Thanks
Mike

**Comment by artursv** [comment]
Yeah, that would really be an edge of an edge case where customer would like to have the site hosted on their own server which has a different timezone set. But I guess we can worry about that when (and if that ever happens).

Meanwhile here is another connection related issue: 

> Feb 01 15:34:02 mysite.com drupal.log:  Feb  1 15:34:02 front-1 drupal: https://mysite.com|1485956042|warden|xx.xxx.xxx.xx]https://mysite.com/fi/fi/admin/reports/warden||0||Update request denied: request body is empty or missing the security token

The security token is set in the settings.php file and I have double checked that it`s correct.

**Comment by mikeddeeson** [comment]
With your latest connection issue, this error message occurs when the request from the Warden server is either not a POST request or the token is not set in the request.

Do you get this error message when the Warden server is trying to get the latest information from the site or when you visit the URL directly in the browser?

**Comment by artursv** [comment]
This happens when server is trying to request information.

**Comment by mikeddeeson** [comment]
OK, within the Warden server when you edit the site, does it have a value for the token or is it empty?

**Comment by mikeddeeson** [comment]
OK thanks, this is a bit strange.

There is a validation check which generates this error message. This occurs when the request from the Warden server is either an empty HTTP POST request or the HTTP POST request key of `token` is empty.

Could you do some debugging of the Warden Drupal module to log the contents of the HTTP POST request to see if it is valid and if there is a key of `token` in it?

**Comment by artursv** [comment]
Hi,

Since it is a production site I can`t poke the code too much but It seems that the whole $_POST variable is empty in this case.

A.

**Comment by mikeddeeson** [comment]
Hi @artursv,

From what you have said previously about your other sites working correctly, I presume that this is still the case and that it is still just this one site that is having issues?

A HTTP POST request is normally made from the Warden server to the site to get the details. Could there be any reason that a POST request could be cleared or reset within the network through to the server that the site sits on that could cause this empty POST variable?

Thanks
Mike

**Comment by mikeddeeson** [comment]
Hi @artursv,

Are you still having issues with this?

I have come across this same error happening recently on a site that I was working with. It turned out that the site had been updated to move from HTTP to HTTPS and there was a redirect in place to redirect the HTTP to HTTPS. Because the URL hadn't been updated in Warden for this site the POST request from Warden server was being redirected which then lost the POST data.

Not sure if this provides any help in pointing you to why this issue is occurring?

**Comment by artursv** [comment]
Hello,

Yes, we still have the issue with this particular site. Because it's a one lonely site not working we have left it as it is because it is in line for a server upgrade which might _resolve_ the problem. This will probably not be the case you described as the site have been on HTTPS since the beginning. 

I think we can close this issue for now. If anything new comes up I will re-open it if the issue fits the general topic here. 

A.

**Comment by mikeddeeson** [comment]
Thanks for the update @artursv - do let me know if you have any further issues and detail and I will see if I can help 😄
